from __future__ import annotations

EXPERIMENTS = {
    "raw_fill": {
        "num": "01",
        "title": "Raw Fill Rates",
        "question": "How often do FVGs actually get revisited?",
        "summary": "Measures near-edge touch, midpoint mitigation, full fill, and eventual revisit before any control comparison.",
        "takeaway": "FVGs are revisited very frequently in absolute terms, but this experiment alone cannot establish that the FVG label is special.",
        "runner": "detailed",
        "sources": ["src/original/fvg_final_fast.py"],
        "method": [
            "Detect each 1-minute FVG only after candle C closes.",
            "Exclude roll-neighborhood events and require valid ATR/state history.",
            "Measure near-edge touch, midpoint mitigation, and full fill over fixed forward horizons.",
            "Measure eventual touch/full fill within the available sample.",
            "Interpret this descriptively; matched controls are required to test whether FVGs are unusually attractive.",
        ],
        "limitations": "High unconditional fill rates can be explained partly by distance, volatility, and ordinary price revisitation. This is a descriptive baseline, not a causal test.",
    },
    "matched_attraction": {
        "num": "02",
        "title": "Matched-Zone Attraction",
        "question": "Are FVGs reached more often than comparable ordinary zones?",
        "summary": "Preserves zone geometry and broad market state while moving the target to matched non-FVG timestamps.",
        "takeaway": "The largest excess attraction appears shortly after formation and decays toward zero at longer horizons.",
        "runner": "multi",
        "sources": ["src/original/fvg_final_fast.py", "src/original/fvg_strength_one_tf.py"],
        "method": [
            "Sample real FVGs using fixed random seeds.",
            "Use non-FVG formation bars as control candidates.",
            "Match session, time bucket, volatility regime, and trend regime.",
            "Copy direction, ATR-normalized width, and ATR-normalized starting distance to each control zone.",
            "Measure FVG and control touches over identical horizons.",
            "Average controls at the parent-FVG level before paired comparisons where the canonical script does so.",
        ],
        "limitations": "Matching reduces obvious confounding but cannot prove causality, and the published scripts retain several weighting/censoring limitations documented in the scientific audit.",
    },
    "age_decay": {
        "num": "03",
        "title": "FVG Age Decay",
        "question": "Does an old unfilled gap still carry information?",
        "summary": "Conditions on gaps that survived untouched and asks whether the remaining FVGs continue to outperform controls.",
        "takeaway": "The incremental attraction is front-loaded; the published 1m advantage weakens rapidly after the first few bars.",
        "runner": "multi",
        "sources": ["src/original/fvg_strength_one_tf.py"],
        "method": [
            "Reuse real FVGs and matched ordinary controls.",
            "Evaluate cumulative touches at 1, 3, 5, 10, and 20 native bars.",
            "For each age interval, keep only zones that were still untouched at the interval start.",
            "Compare the conditional probability of a new touch before the next horizon.",
        ],
        "limitations": "The canonical control calculation is survivor-zone weighted rather than perfectly parent-paired; see docs/SCIENTIFIC_AUDIT.md.",
    },
    "continuation": {
        "num": "04",
        "title": "Formation Continuation",
        "question": "Does creating an FVG predict continuation in the same direction?",
        "summary": "Matches FVG-forming displacement to similar non-FVG moves and compares subsequent signed returns.",
        "takeaway": "Continuation effects are small and inconsistent across timeframes in the published sample.",
        "runner": "multi",
        "sources": ["src/original/fvg_strength_one_tf.py"],
        "method": [
            "Measure three-bar displacement and middle-candle body size in ATR units.",
            "Match non-FVG moves by market state, direction, move size, and body size.",
            "Measure signed ATR-normalized return after 1, 3, 5, and 10 native bars.",
            "Compare both mean continuation and positive-return frequency.",
        ],
        "limitations": "Small conditional return differences can be dominated by costs, execution, and regime changes; statistical predictability does not imply a tradable edge.",
    },
    "retest": {
        "num": "05",
        "title": "First-Touch Retest Reaction",
        "question": "Does price react differently once it reaches an FVG?",
        "summary": "Treats the FVG as a possible temporary support/resistance region instead of only a magnet.",
        "takeaway": "The published reaction advantage is positive but modest across the tested timeframes.",
        "runner": "multi",
        "sources": ["src/original/fvg_strength_one_tf.py"],
        "method": [
            "Search up to 20 native bars for the first near-edge touch.",
            "Set the far edge as full traversal and a one-gap-width rejection target on the opposite side.",
            "Begin race resolution after the touch bar.",
            "Classify rejection first as success, full traversal first as failure, and same-bar hits as ambiguous.",
            "Also measure normalized close displacement three bars after touch.",
        ],
        "limitations": "OHLC bars cannot reveal within-bar ordering when both boundaries trade in the same bar; ambiguity is preserved rather than invented.",
    },
    "midpoint": {
        "num": "06",
        "title": "Midpoint / Consequent Encroachment",
        "question": "Is the exact 50% level special?",
        "summary": "Starts a symmetric near-edge-versus-far-edge race after the exact FVG midpoint trades.",
        "takeaway": "Midpoint reaction differences vary materially by timeframe, with the largest published cell appearing on 4H.",
        "runner": "midpoint",
        "sources": ["src/original/fvg_midpoint_reaction.py"],
        "method": [
            "Resample the active series using the CME 18:00 ET anchor.",
            "Sample eligible FVGs with the canonical fixed seed and create state-matched controls.",
            "Search for the exact midpoint to trade within 20 native bars.",
            "From the next bar, race the equidistant near and far boundaries.",
            "Treat same-bar near/far hits as ambiguous.",
        ],
        "limitations": "A large result in one timeframe should not be interpreted independently of the other searched cells or the broader multiple-testing problem.",
    },
    "body_acceptance": {
        "num": "07",
        "title": "Candle-Body Acceptance Around CE",
        "question": "Does body-close depth inside the gap matter?",
        "summary": "Tests opposite-colored candles that wick into the FVG and classifies their body close by penetration depth.",
        "takeaway": "The highlighted 4H 45–50% cell is interesting but explicitly exploratory rather than a confirmed trading edge.",
        "runner": "ce",
        "sources": ["src/original/fvg_ce_rejection_study.py"],
        "method": [
            "Build 1m through daily bars from the active one-minute series.",
            "Require an opposite-colored signal candle whose wick enters the FVG and whose close remains inside it.",
            "Normalize close depth from 0% at the near edge to 100% at the far edge.",
            "Enter at signal close, target the near edge, and stop at the far edge.",
            "Resolve every higher-timeframe trade on future one-minute bars and mark same-minute TP/SL as ambiguous.",
        ],
        "limitations": "Many timeframe/depth cells were inspected and trade rows are not fully independent; the strongest selected cell is hypothesis-generating.",
    },
    "controls_regimes": {
        "num": "08",
        "title": "Distance, Regimes & Controlled Model",
        "question": "How much does the FVG label matter after obvious variables are controlled?",
        "summary": "Stratifies matched attraction and fits a controlled logistic model with FVG status alongside distance, size, and market-state variables.",
        "takeaway": "Distance explains much of the raw attraction; the conditional FVG effect remains small in the published 60-minute model.",
        "runner": "detailed",
        "sources": ["src/original/fvg_final_fast.py"],
        "method": [
            "Start from the detailed matched 1m sample and use the 60-minute touch outcome.",
            "Stratify by distance, width, session, direction, volatility, trend, displacement, and year.",
            "Repeat under multiple minimum-gap-size filters.",
            "Fit logistic regression using FVG status alongside normalized geometry and market-state features.",
            "Report exp(beta_FVG) as the conditional FVG odds ratio.",
        ],
        "limitations": "A regression coefficient is conditional on the chosen feature set and does not establish an economic or causal edge.",
    },
    "oos": {
        "num": "09",
        "title": "Chronological Robustness",
        "question": "Does the observed effect survive later data?",
        "summary": "Uses chronological early-versus-late splits to expose non-stationarity rather than random shuffling.",
        "takeaway": "Several effects weaken materially in the later sample, which is consistent with a small and regime-dependent signal rather than a stable law.",
        "runner": "oos",
        "sources": ["src/original/fvg_final_fast.py", "src/original/fvg_strength_one_tf.py"],
        "method": [
            "Sort matched parent events chronologically.",
            "Use the first 70% as the early sample and the final 30% as the later sample.",
            "Recompute the five-native-bar matched attraction effect by timeframe.",
            "Run a separate deep 1m 60-minute chronological split.",
            "Report year-level stability from the detailed 1m study.",
        ],
        "limitations": "This is a chronological robustness split, not a sealed prospective pipeline holdout; controls were constructed before the split in the canonical scripts.",
    },
}

ORDER = list(EXPERIMENTS)

RUNNER_TO_STUDY = {
    "detailed": "detailed-1m",
    "multi": "multi-tf",
    "midpoint": "midpoint",
    "ce": "ce-body",
}

TF_LABELS = {1: "1m", 5: "5m", 15: "15m", 60: "1H", 240: "4H"}
CE_TIMEFRAMES = [1, 2, 3, 5, 10, 15, 30, 60, 120, 240, 360, 480, 720, 1440]
